services:
  - type: web
    name: themora-backend
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: DB_NAME
        sync: false
      - key: APP_KEY
        generateValue: true
